#! /bin/bash
# SPDX-License-Identifier: GPL-2.0-or-later
# Copyright (c) 2020, Oracle and/or its affiliates.  All Rights Reserved.
#
# FS QA Test No. 1215
#
# Test swapext with the dry run flag doesn't change anything.

seq=`basename $0`
seqres=$RESULT_DIR/$seq
echo "QA output created by $seq"

here=`pwd`
tmp=/tmp/$$
status=1    # failure is the default!
trap "_cleanup; exit \$status" 0 1 2 3 15

_cleanup()
{
	cd /
	rm -r -f $tmp.* $dir
}

# get standard environment, filters and checks
. ./common/rc
. ./common/filter
. ./common/reflink

# real QA test starts here
_supported_os Linux
_require_test_program "punch-alternating"
_require_xfs_io_command swapext '-v vfs'
_require_scratch
_require_scratch_shutdown

rm -f $seqres.full

_scratch_mkfs >> $seqres.full
_scratch_mount

_pwrite_byte 0x58 0 2m $SCRATCH_MNT/a >> $seqres.full
_pwrite_byte 0x59 0 2m $SCRATCH_MNT/b >> $seqres.full
$here/src/punch-alternating $SCRATCH_MNT/a
$here/src/punch-alternating $SCRATCH_MNT/a

md5sum $SCRATCH_MNT/a $SCRATCH_MNT/b | _filter_scratch

echo dry run swap | tee -a $seqres.full
$XFS_IO_PROG -c "swapext -v vfs -n -e -f -u $SCRATCH_MNT/a" $SCRATCH_MNT/b
_scratch_cycle_mount

md5sum $SCRATCH_MNT/a $SCRATCH_MNT/b | _filter_scratch

# success, all done
status=0
exit
