#! /bin/bash
# SPDX-License-Identifier: GPL-2.0
# Copyright (c) 2025 Oracle.  All Rights Reserved.
#
# FS QA Test 1222
#
# Validate multi-fsblock atomic write support with simulated hardware support
#
. ./common/preamble
_begin_fstest auto quick rw atomicwrites

. ./common/scsi_debug
. ./common/atomicwrites

_cleanup()
{
	_scratch_unmount &>/dev/null
	_put_scsi_debug_dev &>/dev/null
	cd /
	rm -r -f $tmp.*
}

_require_scsi_debug
_require_scratch_nocheck
# Format something so that ./check doesn't freak out
_scratch_mkfs >> $seqres.full

# 512b logical/physical sectors, 512M size, atomic writes enabled
dev=$(_get_scsi_debug_dev 512 512 0 512 "atomic_wr=1")
test -b "$dev" || _notrun "could not create atomic writes scsi_debug device"

export SCRATCH_DEV=$dev
unset USE_EXTERNAL

_require_scratch_write_atomic
_require_atomic_write_test_commands

echo "scsi_debug atomic write properties" >> $seqres.full
$XFS_IO_PROG -c "statx -r -m $STATX_WRITE_ATOMIC" $SCRATCH_DEV >> $seqres.full

_scratch_mkfs >> $seqres.full
_scratch_mount
test "$FSTYP" = "xfs" && _xfs_force_bdev data $SCRATCH_MNT

testfile=$SCRATCH_MNT/testfile
touch $testfile

echo "filesystem atomic write properties" >> $seqres.full
$XFS_IO_PROG -c "statx -r -m $STATX_WRITE_ATOMIC" $testfile >> $seqres.full

sector_size=$(blockdev --getss $SCRATCH_DEV)
min_awu=$(_get_atomic_write_unit_min $testfile)
max_awu=$(_get_atomic_write_unit_max $testfile)

$XFS_IO_PROG -f -c "falloc 0 $((max_awu * 2))" -c fsync $testfile

# try outside the advertised sizes
echo "two EINVAL for unsupported sizes"
min_i=$((min_awu / 2))
_simple_atomic_write $min_i $min_i $testfile -d
max_i=$((max_awu * 2))
_simple_atomic_write $max_i $max_i $testfile -d

# try all of the advertised sizes
echo "all should work"
for ((i = min_awu; i <= max_awu; i *= 2)); do
	$XFS_IO_PROG -f -c "falloc 0 $((max_awu * 2))" -c fsync $testfile
	_test_atomic_file_writes $i $testfile
	_simple_atomic_write $i $i $testfile -d
done

# does not support buffered io
echo "one EOPNOTSUPP for buffered atomic"
_simple_atomic_write 0 $min_awu $testfile

# does not support unaligned directio
echo "one EINVAL for unaligned directio"
_simple_atomic_write $sector_size $min_awu $testfile -d

_scratch_unmount
_put_scsi_debug_dev

# success, all done
echo Silence is golden
status=0
exit
