#! /bin/bash
# SPDX-License-Identifier: GPL-2.0
# Copyright (c) 2017 Christoph Hellwig.  All Rights Reserved.
#
# FS QA Test 463
#
# Test racy COW AIO write completions.
#
. ./common/preamble
_begin_fstest auto quick clone

# Override the default cleanup function.
_cleanup()
{
	cd /
	rm -f $tmp.*
	rm -f $TEST_DIR/file $TEST_DIR/clone
}

# Import common functions.
. ./common/filter
. ./common/reflink

_supported_fs generic

_require_test
_require_test_reflink
_require_aiodio aio-dio-cow-race

$AIO_TEST $TEST_DIR/file $TEST_DIR/clone
res=$?

if [ $res -ne 0 ]; then
	echo "res $res" >> $seqres.full
	xfs_info $TEST_DIR &>> $seqres.full
	stat $TEST_DIR/file $TEST_DIR/clone >> $seqres.full
fi

echo "Silence is golden"
status=0
exit
