#! /bin/bash
# SPDX-License-Identifier: GPL-2.0
#
# FS QA Test No. 759
#
# fsx exercising reads/writes from userspace buffers
# backed by hugepages
#
. ./common/preamble
_begin_fstest rw auto quick

. ./common/filter

_require_test
_require_thp

$FSX_PROG -N 0 -h $TEST_DIR 2>&1 | grep -q 'MADV_COLLAPSE not supported' && \
	_notrun "fsx binary does not support MADV_COLLAPSE"

run_fsx -N 10000            -l 500000 -h
run_fsx -N 10000  -o 8192   -l 500000 -h
run_fsx -N 10000  -o 128000 -l 500000 -h

status=0
exit
