#! /bin/bash
# SPDX-License-Identifier: GPL-2.0
#
# FS QA Test No. 760
#
# fsx exercising direct IO reads/writes from userspace buffers
# backed by hugepages
#
. ./common/preamble
_begin_fstest rw auto quick

. ./common/filter

_require_test
_require_odirect
_require_thp

$here/ltp/fsx -N 0 -h $TEST_DIR 2>&1 | grep -q 'MADV_COLLAPSE not supported' && \
	_notrun "fsx binary does not support MADV_COLLAPSE"

psize=`$here/src/feature -s`
bsize=`$here/src/min_dio_alignment $TEST_DIR $TEST_DEV`

run_fsx -N 10000            -l 500000 -r PSIZE -t BSIZE -w BSIZE -Z -R -W -h
run_fsx -N 10000  -o 8192   -l 500000 -r PSIZE -t BSIZE -w BSIZE -Z -R -W -h
run_fsx -N 10000  -o 128000 -l 500000 -r PSIZE -t BSIZE -w BSIZE -Z -R -W -h

status=0
exit
