#! /bin/bash
# SPDX-License-Identifier: GPL-2.0
# Copyright (c) 2000-2005 Silicon Graphics, Inc.  All Rights Reserved.
#
# FS QA Test No. 116
#
# pv#940491
# Test out resetting of sb_qflags when mounting with no quotas after
# having mounted with quotas.
#
. ./common/preamble
_begin_fstest quota auto quick

# Import common functions.
. ./common/filter
. ./common/quota

# real QA test starts here

_supported_fs xfs

_require_scratch
_require_xfs_quota

# Only mount with the quota options we specify below
_qmount_option "defaults"

_scratch_mkfs >/dev/null 2>&1

echo mount with uquota >> /dev/ttyprintk
_scratch_mount "-o uquota"
_scratch_unmount
$UDEV_SETTLE_PROG >/dev/null 2>&1
echo unmount with uquota >> /dev/ttyprintk

#_scratch_xfs_db -r -c sb -c print  | grep qflags
_scratch_xfs_db -r -c sb -c print &> /tmp/farts
if grep 'qflags = 0$' /tmp/farts; then
	cat /tmp/farts
	for ((i = 0; i < 30; i++)); do
		_scratch_xfs_db -r -c sb -c print | grep -E '(crc|lsn|qflags)'
		sleep 1
	done
	echo BAH
else
	grep qflags /tmp/farts
fi

echo mount with noquota >> /dev/ttyprintk
_scratch_mount
_scratch_unmount
echo unmount with noquota >> /dev/ttyprintk

_scratch_xfs_db -r -c sb -c print  | grep qflags

# success, all done
status=0
exit
