#! /bin/bash
# SPDX-License-Identifier: GPL-2.0
# Copyright (c) 2024 Oracle.  All Rights Reserved.
#
# FS QA Test 1889
#
# Functional testing for mkfs applying self_healing fs property and xfs_scrub
# changing its behavior accordingly.  Or at least claiming to.
#
. ./common/preamble
_begin_fstest auto

. ./common/filter
. ./common/fuzzy

_require_test
_require_xfs_spaceman_command listfsprops	# needed for fs props
_require_xfs_db_command attr_get
_require_scrub

_cleanup()

{
	cd /
	rm -r -f $tmp.*
	_umount $dummymnt &>/dev/null
	rmdir $dummymnt
	rm -f $dummyfile
}

dummyfile=$TEST_DIR/$seq.somefile
dummymnt=$TEST_DIR/$seq.mount

truncate -s 10g $dummyfile
mkdir -p $dummymnt

testme() {
	local mkfs_args=('-f')
	local value="$1"
	test -n "$value" && value="=$value"

	if [ $# -gt 0 ]; then
		mkfs_args+=('-m' "self_healing$value")
	fi

	echo "testing ${mkfs_args[*]}" >> $seqres.full

	$MKFS_XFS_PROG "${mkfs_args[@]}" $dummyfile >> $seqres.full || \
		_notrun "mkfs.xfs ${mkfs_args[*]} failed?"

	_mount -o loop $dummyfile $dummymnt
	XFS_SCRUB_PHASE=7 $XFS_SCRUB_PROG -d -o fsprops_advise $dummymnt 2>&1 | \
		grep self_healing | _filter_test_dir | sed -e 's/\(directive.\).*$/\1/g'
	_umount $dummymnt
}

testme ''
testme
testme none
testme check
testme optimize
testme repair
testme 0
testme 1

status=0
exit
