#! /bin/bash
# SPDX-License-Identifier: GPL-2.0-or-later
# Copyright (c) 2024-2025 Oracle.  All Rights Reserved.
#
# FS QA Test No. 1898
#
# Check that xfs_healer can report filesystem shutdowns.

. ./common/preamble
_begin_fstest auto quick scrub eio selfhealing

. ./common/fuzzy
. ./common/filter
. ./common/systemd

_require_scratch_nocheck
_require_scrub
_require_command "$XFS_HEALER_PROG" "xfs_healer"

_scratch_mkfs >> $seqres.full
_scratch_mount
$XFS_IO_PROG -f -c "pwrite -S 0x58 0 500k" -c "fsync" $victim >> $seqres.full

echo "Start healer and shut down"
_scratch_invoke_healer "$tmp.healer"
_scratch_shutdown -f

# Unmount filesystem to start fresh
echo "Kill healer"
_scratch_kill_healer
cat $tmp.healer >> $seqres.full
cat $tmp.healer | _filter_scratch | grep 'shut down'

# success, all done
status=0
exit
