#! /bin/bash
# SPDX-License-Identifier: GPL-2.0
# Copyright (c) 2008 Silicon Graphics, Inc.  All Rights Reserved.
#
# FS QA Test No. 216
#
# log size mkfs test - ensure the log size scaling works for small filesystems
#
. ./common/preamble
_begin_fstest log metadata auto quick

# Import common functions.
. ./common/filter

# real QA test starts here
_supported_fs xfs

_require_scratch
_scratch_mkfs_xfs >/dev/null 2>&1
_scratch_mount

_require_loop
LOOP_DEV=$SCRATCH_MNT/test_fs
LOOP_MNT=$SCRATCH_MNT/test_fs_dir

loop_mkfs_opts=
$MKFS_XFS_PROG 2>&1 | grep -q rmapbt && \
	loop_mkfs_opts="$loop_mkfs_opts -m rmapbt=0"
$MKFS_XFS_PROG 2>&1 | grep -q reflink && \
	loop_mkfs_opts="$loop_mkfs_opts -m reflink=0"

_do_mkfs()
{
	for i in $*; do
		echo -n "fssize=${i}g "
		$MKFS_XFS_PROG -f -b size=4096 -l version=2 \
			-d name=$LOOP_DEV,size=${i}g $loop_mkfs_opts |grep log
		mount -o loop -t xfs $LOOP_DEV $LOOP_MNT
		echo "test write" > $LOOP_MNT/test
		umount $LOOP_MNT > /dev/null 2>&1
	done
}
# make large holey file
$XFS_IO_PROG -f -c "truncate 256g" $LOOP_DEV

# link correct .out file, since default log sizes changed when bigtime was
# turned on by default
$MKFS_XFS_PROG -N -f -b size=4096 -l version=2 \
	-d name=$LOOP_DEV $loop_mkfs_opts &> $tmp.mkfs
seqfull=$0
rm -f $seqfull.out
if grep -qw 'bigtime=1' $tmp.mkfs; then
	ln -s $seq.out.bigtime $seqfull.out
else
	ln -s $seq.out.old $seqfull.out
fi

#make loopback mount dir
mkdir $LOOP_MNT

# walk over standard sizes (up to 256GB)
_do_mkfs 1 2 4 8 16 32 64 128 256

status=0
exit
