#! /bin/bash
# SPDX-License-Identifier: GPL-2.0
# Copyright (c) 2014 Red Hat, Inc.  All Rights Reserved.
# Copyright (c) 2019 Oracle, Inc.  All Rights Reserved.
#
# FS QA Test No. 744
#
# Use the xfs_io bulkstat utility to verify bulkstat finds all inodes in a
# filesystem.  Test under various inode counts, inobt record layouts and
# bulkstat batch sizes.
#
seq=`basename $0`
seqres=$RESULT_DIR/$seq
echo "QA output created by $seq"

here=`pwd`
tmp=/tmp/$$
status=1	# failure is the default!
trap "_cleanup; exit \$status" 0 1 2 3 15

_cleanup()
{
    cd /
    rm -f $tmp.*
}

# print the number of inodes counted by bulkstat
_bstat_count()
{
	local batchsize="$1"
	local tag="$2"

	echo -n "$tag: "
	$XFS_IO_PROG -c "bulkstat -n $batchsize" $SCRATCH_MNT | grep ino | wc -l
}

# print the number of inodes counted by per-ag bulkstat
_bstat_perag_count()
{
	local batchsize="$1"
	local tag="$2"

	local agcount=$(_xfs_mount_agcount $SCRATCH_MNT)
	echo -n "$tag: "
	seq 0 $((agcount - 1)) | while read ag; do
		$XFS_IO_PROG -c "bulkstat -a $ag -n $batchsize" $SCRATCH_MNT
	done | grep ino | wc -l
}

# Sum the number of allocated inodes in a fs...
_inumbers_ag()
{
	local agcount="$1"
	local batchsize="$2"
	local mount="$3"

	seq 0 $((agcount - 1)) | while read ag; do
		$XFS_IO_PROG -c "inumbers -a $ag -n $batchsize" $mount
	done | grep alloccount | awk '{x += $3} END { print(x) }'
}

# print the number of inodes counted by inumbers
_inumbers_count()
{
	local expect="$1"

	# There probably aren't more than 10 hidden inodes, right?
	local tolerance=10

	# Force all background inode cleanup
	_scratch_cycle_mount

	echo -n "inumbers all: "
	nr=$($XFS_IO_PROG -c "inumbers" $SCRATCH_MNT | grep alloccount | \
		awk '{x += $3} END { print(x) }')
	_within_tolerance "inumbers" $nr $expect $tolerance -v

	local agcount=$(_xfs_mount_agcount $SCRATCH_MNT)
	for batchsize in 64 2 1; do
		echo -n "inumbers $batchsize: "
		nr=$(_inumbers_ag $agcount $batchsize $SCRATCH_MNT)
		_within_tolerance "inumbers" $nr $expect $tolerance -v
	done
}

# compare the src/bstat output against the xfs_io bstat output
_bstat_compare()
{
	diff -u <(./src/bstat $SCRATCH_MNT | grep ino | awk '{print $2}') \
		<($XFS_IO_PROG -c 'bulkstat' $SCRATCH_MNT | grep ino | awk '{print $3}')
}

# print bulkstat counts using varied batch sizes
_bstat_test()
{
	expect=`find $SCRATCH_MNT -print | wc -l`
	echo
	echo "expect $expect"

	for sz in 4096 71 32 1; do
		_bstat_count $sz "$sz all"
		_bstat_perag_count $sz "$sz perag"
		_bstat_compare
		_inumbers_count $expect
	done
}

# get standard environment, filters and checks
. ./common/rc
. ./common/filter

_require_scratch
_require_xfs_io_command bulkstat
_require_xfs_io_command bulkstat_single
_require_xfs_io_command inumbers

# real QA test starts here

_supported_fs xfs
_supported_os Linux

rm -f $seqres.full

DIRCOUNT=8
INOCOUNT=$((2048 / DIRCOUNT))

_scratch_mkfs "-d agcount=$DIRCOUNT" >> $seqres.full 2>&1 || _fail "mkfs failed"
_scratch_mount

# who is the root inode?
bs_root=$($XFS_IO_PROG -c 'bulkstat_single root' $SCRATCH_MNT 2> /dev/null | grep ino | \
	awk '{print $3}')
stat_root=$(stat -c '%i' $SCRATCH_MNT)
if [ -n "$bs_root" ] && [ "$stat_root" -ne "$bs_root" ]; then
	echo "stat says root is $stat_root but bulkstat says $bs_root"
fi

# create a set of directories and fill each with a fixed number of files
for dir in $(seq 1 $DIRCOUNT); do
	mkdir -p $SCRATCH_MNT/$dir
	for i in $(seq 1 $INOCOUNT); do
		touch $SCRATCH_MNT/$dir/$i
	done
done
_bstat_test

# remove every other file from each dir
for dir in $(seq 1 $DIRCOUNT); do
	for i in $(seq 2 2 $INOCOUNT); do
		rm -f $SCRATCH_MNT/$dir/$i
	done
done
_bstat_test

# remove the entire second half of files
for dir in $(seq 1 $DIRCOUNT); do
	for i in $(seq $((INOCOUNT / 2)) $INOCOUNT); do
		rm -f $SCRATCH_MNT/$dir/$i
	done
done
_bstat_test

# remove all regular files
for dir in $(seq 1 $DIRCOUNT); do
	rm -f $SCRATCH_MNT/$dir/*
done
_bstat_test

# success, all done
status=0
exit
