#! /bin/bash
# SPDX-License-Identifier: GPL-2.0-or-later
# Copyright (c) 2021 Oracle.  All Rights Reserved.
#
# FS QA Test No. 768
#
# Make sure that the kernel won't mount a filesystem if repair forcibly sets
# NEEDSREPAIR while fixing a directory.  Corrupt a directory in such a way as
# to force repair to write an invalid dirent value as a sentinel to trigger a
# repair activity in a later phase.  Use a debug knob in xfs_repair to abort
# the repair immediately after forcing the flag on.

seq=`basename $0`
seqres=$RESULT_DIR/$seq
echo "QA output created by $seq"

here=`pwd`
tmp=/tmp/$$
status=1    # failure is the default!
trap "_cleanup; exit \$status" 0 1 2 3 15

_cleanup()
{
	cd /
	rm -f $tmp.* $fake_logfile $fake_rtfile
}

# get standard environment, filters and checks
. ./common/rc
. ./common/filter

# real QA test starts here
_supported_fs xfs
_require_scratch
_require_xfs_repair_upgrade needsrepair

rm -f $seqres.full

# Forcibly format a V5 filesystem.  If the tooling supports needsrepair then
# the kernel and userspace ought to be new enough to handle V5.  Make sure the
# debug knob is actually present before we run the real directory corruption
# scenario.
_scratch_mkfs -m crc=1 >> $seqres.full
_scratch_xfs_repair -c needsrepair=1 -o debug_force_needsrepair_abort=1 2>> $seqres.full
test $? -eq 55 || _notrun "xfs_repair doesn't support needsrepair debug knob"

# Set up a real filesystem for our actual test
_scratch_mkfs -m crc=1 >> $seqres.full

# Create a directory large enough to have a dir data block.  2k worth of
# dirent names ought to do it.
_scratch_mount
mkdir -p $SCRATCH_MNT/fubar
for i in $(seq 0 256 2048); do
	fname=$(printf "%0255d" $i)
	ln -s -f urk $SCRATCH_MNT/fubar/$fname
done
inum=$(stat -c '%i' $SCRATCH_MNT/fubar)
_scratch_unmount

# Fuzz the directory
_scratch_xfs_db -x -c "inode $inum" -c "dblock 0" \
	-c "fuzz -d bu[2].inumber add" >> $seqres.full

# Try to repair the directory, force it to crash after setting needsrepair
_scratch_xfs_repair -o debug_force_needsrepair_abort 2>> $seqres.full
test $? -eq 55 || echo "debug knob should have returned 55??"
_scratch_xfs_db -c 'version' >> $seqres.full

# We can't mount, right?
_scratch_xfs_db -c 'version' | grep -q NEEDSREPAIR || \
	echo "NEEDSREPAIR should be set on superblock"
_try_scratch_mount 2>&1 | _filter_scratch
if [ $? -ne 0 ]; then
	echo "Should not be able to mount after needsrepair crash"
	_scratch_unmount
fi

# Repair properly this time and retry the mount
_scratch_xfs_repair 2>> $seqres.full
_scratch_xfs_db -c 'version' >> $seqres.full
_scratch_xfs_db -c 'version' | grep -q NEEDSREPAIR && \
	echo "NEEDSREPAIR should not be set on superblock"

_scratch_mount

# success, all done
status=0
exit
