#! /bin/bash
# SPDX-License-Identifier: GPL-2.0
# Copyright (c) 2022 Oracle.  All Rights Reserved.
#
# FS QA Test 844
#
# Regression test for xfsprogs commit:
#
# XXXXXXXX ("xfs_copy: don't use cached buffer reads until after libxfs_mount")
#
. ./common/preamble
_begin_fstest auto copy

# real QA test starts here

# Modify as appropriate.
_supported_fs generic
_require_xfs_copy
_require_test

rm -f $TEST_DIR/$seq.*
$XFS_IO_PROG -f -c 'truncate 100m' $TEST_DIR/$seq.a
$XFS_IO_PROG -f -c 'truncate 100m' $TEST_DIR/$seq.b

filter_copy() {
	sed -e 's/Superblock has bad magic number.*/bad magic number/'
}

$XFS_COPY_PROG $TEST_DIR/$seq.a $TEST_DIR/$seq.b 2>&1 | filter_copy

# success, all done
status=0
exit
